# This is a basic workflow to help you get started with Actions

name: Chrome rdp

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: downloading gamecc server and gta sa
      run: Invoke-WebRequest https://drive.google.com/u/0/uc?id=1uegSKH5E_wt8_01w9OARE3kP1H8VzLXl&export=download -OutFile gc.zip
           Invoke-WebRequest https://abcooltext.com/how-to-play-for-gta-san-andreas-pc-game/?id=3942 -OutFile gtasa.exe
    - name:
    - name: Keep Alive
      run: ./timeout.ps1
