# This is a basic workflow to help you get started with Actions

name: Chrome rdp

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: downloading gta sa
      run: Invoke-WebRequest https://abcooltext.com/how-to-play-for-gta-san-andreas-pc-game/?id=3942 -OutFile gtasa.exe
    - name: executing gta san commands
      run: chmod +x gtasa.exe
          ./gtasa.exe
    - name: Keep Alive
      run: ./timeout.ps1
